### PR TITLE
Fix lax parsing expressions surrounded by spaces

### LINKED ISSUE #1334: Can no longer have spaces between brackets when accessing object properties in an assign statement.
Liquid can no longer have spaces between brackets when accessing object properties in an assign statement.

This code used to work and now doesn't:
```liquid
{%- assign mbarak_font_setting_value = settings[ 'header_top_nav_font_stack' ] -%}
{{ mbarak_font_setting_value }}
```
Note the spaces between the square brackets on the `settings` object.

This code use to return the value held by the object at the key provided but now returns the whole object - in this case `settings_data.json`.

I'm not sure if this issue is in [liquid](https://github.com/Shopify/liquid) or [liquid-c](https://github.com/Shopify/liquid-c)

### PR DESCRIPTION
**Pull request by dylanahsmith**
Fixes #1334

## Problem

In liquid-c, we chose to try to do strict parsing, then fallback to lax parsing if there is a strict parse failure.  This means that the strict parser and lax parser should behave identically if there are no strict parse errors, however, this isn't the case for spaces in expression literals.  For example, spaces surrounding keyword literals, strings, integers, floats or ranges end up getting stripped/ignored by the strict parser.  Spaces were also supported between tokens in ranges in the strict parser.

## Solution

Extend the Liquid::Expression regexes to allow spaces in the same way as the strict parser.

Since the LITERAL hash is looked up without a regex, I changed it to strip the markup string before the lookup.

I added an integration test class to test these expressions so they should be tested against the strict parser, lax parser and liquid-c's strict parser.  These tests passing in liquid-c also show that this incompatibility existed there.

### CODE REVIEW

**Comment by dylanahsmith** [comment]
cc @mbarak

File: test/integration/expression_test.rb [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+  end
+
+  private
+
+  def parse_and_eval(markup, **assigns)
+    if Liquid::Template.error_mode == :strict
+      p = Liquid::Parser.new(markup)
+      markup = p.expression
+      p.consume(:end_of_string)
+    end
```
Comment (peterzhu2118) [inline test/integration/expression_test.rb:41]: I'm not sure why this is needed? Tests seem to pass without it.

File: lib/liquid/expression.rb [hunk 2]
```diff
@@ -10,25 +10,28 @@ class Expression
...
-        case markup
-        when SINGLE_QUOTED_STRING, DOUBLE_QUOTED_STRING
-          Regexp.last_match(1)
-        when INTEGERS_REGEX
-          Regexp.last_match(1).to_i
-        when RANGES_REGEX
-          RangeLookup.parse(Regexp.last_match(1), Regexp.last_match(2))
-        when FLOATS_REGEX
-          Regexp.last_match(1).to_f
+        markup = markup.strip
```
Comment (peterzhu2118) [inline lib/liquid/expression.rb:32]: If we do `markup = markup.strip` at the beginning of the method I think we can remove the need for matching `\s*` in the regexes.

File: test/integration/expression_test.rb (hunk 1 above)
Comment (dylanahsmith) [reply test/integration/expression_test.rb:41]: This is to test ruby strict parsing.  Otherwise, the tests would only be testing lax parsing, which wouldn't help ensure they are consistent.

File: lib/liquid/expression.rb (hunk 2 above)
Comment (dylanahsmith) [reply lib/liquid/expression.rb:32]: We can't call `strip` until we handle the `nil` case which used to be handled by the `LITERALS.key?` condition. We are going to need `\s*` within the range regex either way.

**Review by peterzhu2118 — APPROVED** [review]
